# Generated by Django 3.2.2 on 2021-05-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
